spring:
  application:
    name: mottu
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mottu}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}

logging:
  level:
    org.hibernate.SQL: info

flyway:
  enabled: true
  baseline-on-migrate: true
